project:
  type: website
  output-dir: docs

website:
  title: "Benjamin Valderrama"
  navbar:
     background: primary
     left:
     - href: research.qmd
       text: "Research"
     - href: news.qmd
       text: "News coverage"
     - href: blog.qmd
       text: "My blog"
     - href: saMBA.qmd
       text: "saMBA"
     - href: https://github.com/Benjamin-Valderrama/MVP
       text: "MVP"

format:
  html:
    theme: Lux
    css: styles.css
    toc: true

editor: visual

